# -*- coding: utf-8 -*-
# @Time : 2026/6/10 下午3:15
# @Author : Wang Jun
# @Email: wj_xd@foxmail.com

"""ParaScale v1 public API.

ParaScale now exposes the runtime-first architecture directly. Historical
Engine/ParaEngine and eager parallel wrappers were removed before public
release, so new development should use config, planning, runtime, checkpoint,
data, and serving contracts.
"""

from ._version import PUBLIC_API_VERSION, __version__
from .checkpoint import (
    CheckpointConversionPlan,
    CheckpointConverter,
    CheckpointManager,
    CheckpointManifest,
    CheckpointValidationReport,
    CheckpointValidator,
)
from .config import (
    BackendConfig,
    DataPipelineConfig,
    LayeredParaScaleConfig,
    ParallelConfig,
    ParaScaleConfig,
    QuantizationConfig,
    TrainingRunConfig,
    WorkloadConfig,
)
from .configuration import (
    CURRENT_CONFIG_SCHEMA_VERSION,
    migrate_config_schema,
    validate_config_schema,
)
from .contracts import (
    BackendPlan,
    CheckpointPlan,
    CommunicationPlan,
    DataPlan,
    DevicePlan,
    InferencePlan,
    RuntimePlan,
)
from .core import (
    AscendDeviceBackend,
    ClusterTopology,
    CollectiveBackend,
    CpuDeviceBackend,
    DeviceBackend,
    DeviceSpec,
    MockCollectiveBackend,
    NodeSpec,
    NvidiaDeviceBackend,
    TorchDistributedCollectiveBackend,
)
from .data import (
    BatchEstimate,
    DataLoaderPlan,
    DistributedTokenBudgetBatchSampler,
    ImageFolderProfile,
    LengthBucketSampler,
    MultiModalBatchSchema,
    MultiModalCollator,
    MultiModalDataPipeline,
    PatchTokenBatchSampler,
    ResolutionBucketSampler,
    TokenBudgetBatchSampler,
    VisionCollator,
    VisionMetadataCache,
    VisionThroughputProfile,
    VisionThroughputProfiler,
    build_dataloader_plan,
    estimate_patch_tokens,
    estimate_sample_tokens,
    normalize_multimodal_sample,
    profile_image_folder,
)
from .data.multimodal import (
    ContrastivePairSpec,
    MultiModalTaskSpec,
    TokenCostEstimate,
    VlmLoraSpec,
    estimate_multimodal_token_cost,
)
from .parallel import (
    CompressionStats,
    GradientCompressor,
    IdentityCompressor,
    OneBitCompressor,
    ParallelDimension,
    ParallelPlan,
    SequenceParallelAdapter,
    SequenceParallelConfig,
    SequenceShardSpec,
    TopKCompressor,
    build_gradient_compressor,
    build_parallel_plan,
)
from .runtime import (
    AscendNativeTrainingBackend,
    BenchmarkPlan,
    BenchmarkScenario,
    DeepSpeedTrainingBackend,
    FSDPTrainingBackend,
    InferenceEngine,
    InferenceState,
    LaunchPlan,
    NativeTrainingBackend,
    RuntimeContext,
    TrainEngine,
    TrainingBackend,
    TrainingBackendRegistry,
    TrainState,
    WorkloadDescriptor,
    build_benchmark_plan,
    build_launch_plan,
    build_runtime_context,
    create_runtime_training_backend,
    default_training_backend_registry,
)
from .serving import (
    ContinuousBatchScheduler,
    KVCacheManager,
    SamplingConfig,
    ServeRequest,
    ServeResponse,
    ServingEngine,
)
from .strategy import (
    BatchRuntimeStats,
    HeterogeneousParallelPlan,
    NodeGroup,
    RuntimeProfile,
    StrategyPlan,
    StrategyTuningResult,
    apply_strategy_tuning,
    build_heterogeneous_parallel_plan,
    build_oom_retry_plan,
    build_runtime_profile,
    build_strategy_plan,
    tune_strategy_from_runtime,
)

__all__ = [
    "__version__",
    "PUBLIC_API_VERSION",
    "CURRENT_CONFIG_SCHEMA_VERSION",
    "migrate_config_schema",
    "validate_config_schema",
    "ParaScaleConfig",
    "LayeredParaScaleConfig",
    "WorkloadConfig",
    "ParallelConfig",
    "BackendConfig",
    "DataPipelineConfig",
    "TrainingRunConfig",
    "QuantizationConfig",
    "RuntimePlan",
    "DevicePlan",
    "BackendPlan",
    "CommunicationPlan",
    "DataPlan",
    "CheckpointPlan",
    "InferencePlan",
    "BatchEstimate",
    "DataLoaderPlan",
    "LengthBucketSampler",
    "TokenBudgetBatchSampler",
    "DistributedTokenBudgetBatchSampler",
    "MultiModalBatchSchema",
    "MultiModalCollator",
    "MultiModalDataPipeline",
    "PatchTokenBatchSampler",
    "ResolutionBucketSampler",
    "VisionCollator",
    "ImageFolderProfile",
    "VisionMetadataCache",
    "VisionThroughputProfile",
    "VisionThroughputProfiler",
    "build_dataloader_plan",
    "estimate_patch_tokens",
    "estimate_sample_tokens",
    "profile_image_folder",
    "normalize_multimodal_sample",
    "MultiModalTaskSpec",
    "VlmLoraSpec",
    "ContrastivePairSpec",
    "TokenCostEstimate",
    "estimate_multimodal_token_cost",
    "DeviceBackend",
    "CpuDeviceBackend",
    "NvidiaDeviceBackend",
    "AscendDeviceBackend",
    "CollectiveBackend",
    "MockCollectiveBackend",
    "TorchDistributedCollectiveBackend",
    "DeviceSpec",
    "NodeSpec",
    "ClusterTopology",
    "StrategyPlan",
    "BatchRuntimeStats",
    "RuntimeProfile",
    "StrategyTuningResult",
    "NodeGroup",
    "HeterogeneousParallelPlan",
    "build_runtime_profile",
    "build_strategy_plan",
    "build_heterogeneous_parallel_plan",
    "build_oom_retry_plan",
    "apply_strategy_tuning",
    "tune_strategy_from_runtime",
    "RuntimeContext",
    "WorkloadDescriptor",
    "LaunchPlan",
    "BenchmarkPlan",
    "BenchmarkScenario",
    "build_benchmark_plan",
    "build_launch_plan",
    "build_runtime_context",
    "TrainEngine",
    "TrainState",
    "InferenceEngine",
    "InferenceState",
    "TrainingBackend",
    "AscendNativeTrainingBackend",
    "NativeTrainingBackend",
    "FSDPTrainingBackend",
    "DeepSpeedTrainingBackend",
    "TrainingBackendRegistry",
    "create_runtime_training_backend",
    "default_training_backend_registry",
    "CheckpointManifest",
    "CheckpointManager",
    "CheckpointValidationReport",
    "CheckpointValidator",
    "CheckpointConversionPlan",
    "CheckpointConverter",
    "ServingEngine",
    "ContinuousBatchScheduler",
    "KVCacheManager",
    "SamplingConfig",
    "ServeRequest",
    "ServeResponse",
    "ParallelDimension",
    "ParallelPlan",
    "build_parallel_plan",
    "SequenceParallelAdapter",
    "SequenceParallelConfig",
    "SequenceShardSpec",
    "CompressionStats",
    "GradientCompressor",
    "IdentityCompressor",
    "TopKCompressor",
    "OneBitCompressor",
    "build_gradient_compressor",
]
